#!/bin/bash

#
# Tareas periódicas en departamento
#

playbooks="/home/vcarceler/playbooks"

source <(python -m ara.setup.env)

ansible-playbook -i $playbooks/hosts $playbooks/dpt-inf-u1804.yml
ansible-playbook -i $playbooks/hosts $playbooks/users/informatica-u1804/profesinf-users.yml
