#!/bin/bash

#
# Tareas periódicas en departamento
#

playbooks="/home/vcarceler/playbooks"

source <(python -m ara.setup.env)

ansible-playbook -i $playbooks/hosts $playbooks/fisicaiquimica-users.yml
