#!/bin/bash

#
# Tareas periódicas en los ordenadores de ESOBATX
#

playbooks="/home/vcarceler/playbooks"

source <(python -m ara.setup.env)

ansible-playbook -i $playbooks/hosts $playbooks/aulas-esobat-u1804.yml
