#!/bin/bash

#
# Tareas periódicas en la sala de professors
#

playbooks="/home/vcarceler/playbooks"

source <(python -m ara.setup.env)

ansible-playbook -i $playbooks/hosts $playbooks/saladeguardies-u1804.yml
